host:
  name: localhost

driver:
  h2: org.h2.Driver

url:
  h2: jdbc:h2:mem:testdb;MODE=MYSQL

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${url.h2}
    driver-class-name: ${driver.h2}
    username: sa
    password:

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.sojuton.*.model.dto
  configuration:
    map-underscore-to-camel-case: true


jwt:
  secret-key: 'sojuton'